Gabriel
wellissongomes/projeto-plp pull request #17
Opened 2021-05-15 20:05 UTC by gabrielmbs

2021-05-15 22:42 UTC, wellissongomes commented on prolog/controllers/personController.pl
>    wait.
Aqui ficou com 2 wait. Acho que poderia remover ambos e colocar após onde é chamado esse predicado, como você fez para a listagem de doces e bebidas.

2021-05-15 22:42 UTC, wellissongomes commented on prolog/controllers/personController.pl
>    wait.
O mesmo aqui.

2021-05-15 22:43 UTC, wellissongomes commented on prolog/controllers/purchaseController.pl
>    wait.
Mesmo aqui.

2021-05-15 22:43 UTC, wellissongomes commented on prolog/controllers/purchaseController.pl
>    wait.
Mesmo aqui.

2021-05-15 22:46 UTC, wellissongomes requested changes
Vê o que acha do que falei

2021-05-15 22:57 UTC, gabrielmbs commented on prolog/controllers/personController.pl
>    wait.
Alterei e testei, realmente fica melhor sem.

2021-05-15 22:57 UTC, gabrielmbs commented on prolog/controllers/personController.pl
>    wait.
Alterei e testei, realmente fica melhor sem.

2021-05-15 22:57 UTC, gabrielmbs commented on prolog/controllers/purchaseController.pl
>    wait.
Alterei e testei, realmente fica melhor sem.

2021-05-15 23:02 UTC, gabrielmbs commented on prolog/controllers/purchaseController.pl
>    wait.
Alterei e testei, realmente fica melhor sem.

2021-05-16 02:01 UTC, wellissongomes approved these changes

2021-05-16 02:02 UTC, merged